# Generated by Django 4.2.15 on 2024-08-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truegrit', '0005_videoqualityresolution_videocompressionstandard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionframerole',
            name='abbreviation',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
