# Generated by Django 4.2.15 on 2024-08-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truegrit', '0006_distributionframerole_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionframerole',
            name='abbreviation',
            field=models.CharField(max_length=64),
        ),
    ]
