# Generated by Django 4.2.15 on 2024-08-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truegrit', '0008_installationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoqualityresolution',
            name='abbreviation',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
