# Generated by Django 4.2.15 on 2024-09-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truegrit', '0011_storechain_storelocation_store_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
