# Generated by Django 4.2.15 on 2024-09-18 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('truegrit', '0012_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketArea',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='truegrit.storechain')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='store',
            name='identifier',
        ),
        migrations.AddField(
            model_name='store',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='prefix',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.DeleteModel(
            name='StoreLocation',
        ),
    ]
