# Generated by Django 4.2.15 on 2024-09-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truegrit', '0013_marketarea_remove_store_identifier_store_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='suffix',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
