# Generated by Django 4.2.15 on 2024-09-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truegrit', '0014_store_suffix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='number',
        ),
        migrations.RemoveField(
            model_name='store',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='store',
            name='suffix',
        ),
        migrations.AddField(
            model_name='store',
            name='identifier',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
