# Generated by Django 4.2.15 on 2024-09-18 04:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('truegrit', '0015_remove_store_number_remove_store_prefix_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='BusinessUnit',
        ),
    ]
