# Generated by Django 4.2.15 on 2024-09-18 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('truegrit', '0016_rename_store_businessunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraAssignment',
            fields=[
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='camera',
            name='mac_address',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.DeleteModel(
            name='CameraInstallation',
        ),
        migrations.AddField(
            model_name='cameraassignment',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truegrit.camera'),
        ),
        migrations.AddField(
            model_name='cameraassignment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cameraassignment',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
