# Generated by Django 4.2.15 on 2024-09-18 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truegrit', '0018_network_camera_ip_address_camera_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='business_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='truegrit.businessunit'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
