# Generated by Django 4.2.15 on 2024-09-19 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truegrit', '0019_network_business_unit_alter_businessunit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='market_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='truegrit.marketarea'),
        ),
    ]
