# Generated by Django 4.2.15 on 2024-09-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truegrit', '0020_businessunit_market_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='gateway',
            field=models.GenericIPAddressField(null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='network',
            name='subnet',
            field=models.GenericIPAddressField(null=True, protocol='IPv4'),
        ),
    ]
