# Generated by Django 4.2.15 on 2024-10-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truegrit', '0022_cameraipprocessstatus_cameraipprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='marked_complete',
            field=models.BooleanField(default=False),
        ),
    ]
