# Generated by Django 4.2.15 on 2024-12-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truegrit', '0025_timeentry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='project',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='user',
        ),
    ]
