# Generated by Django 4.2.15 on 2024-12-11 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truegrit', '0026_remove_timeentry_end_time_remove_timeentry_project_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeEntry',
        ),
    ]
