# Generated by Django 4.2.15 on 2024-12-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truegrit', '0028_timeentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='project_description',
        ),
    ]
