# Generated by Django 4.2.15 on 2024-12-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truegrit', '0030_remove_timeentry_user_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
